language: node_js
node_js:
  - 12.11.1
cache: false
branches:
  except:
    - test_reports
before_script:
  npm install zeromq@4.6.0
after_failure:
  chmod +x .travis/push_test_report.sh && .travis/push_test_report.sh
after_success:
  chmod +x .travis/push_test_report.sh && .travis/push_test_report.sh
  chmod +x .travis/publish_release.sh && .travis/publish_release.sh
notifications:
  email:
    recipients:
      - psk.build.track@gmail.com
    on_success: change
    on_failure: always
